// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiojnetajqvnbimxsowx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpb2puZXRhanF2bmJpbXhzb3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjQzMDMsImV4cCI6MjA2MzAwMDMwM30.SVJUokm9VAJ1PLp_KebbqT_3s5CD28NYl854pMv9zqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);